SEARCH_DIR(.\)
SEARCH_DIR(c:\dev-pas\units\)
SEARCH_DIR(c:\dev-pas\units\rtl\)
SEARCH_DIR(c:\dev-pas\bin\)
INPUT(
c:\dev-pas\units\rtl\wprt0.ow
x:\!programming\pascal\lw17\171.ow
)
GROUP(
c:\dev-pas\units\rtl\LIBPOB~2.AW
c:\dev-pas\units\rtl\LIBPSY~2.AW
)
